### ISSUE TITLE
Google Summer of Code 2024

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/frontends-team-compass#234]
Hey all, organization can apply for Google Summer of Code 2024 up to February 6th (**next Tuesday**).

*What do we need to apply?*

- [x] Two contact points: I'm willing to be the main one. So I'm looking for a backup.
- [x] A page listing the ideas: I created a project to be able to link easily to existing resources: https://github.com/orgs/jupyterlab/projects/8/views/1?pane=info  
    Feel free to add your idea *if you are willing to be a mentor*! (time commitment is estimated to 3h/week for 12 weeks)
- ~~Apply to GSoC as organization~~
- [x] After iterating with the NumFocus coordinators, a [single page document](https://github.com/jupyterlab/team-compass/wiki/GSoC-2024) has been created.

Resources:
* https://google.github.io/gsocguides/mentor/
* https://summerofcode.withgoogle.com/

---
cc @jupyterlab/jupyterlab-council for awareness

**Comment by ellisonbg** [comment]
I have done GSoC for a number of years (with SymPy) and had a really great experience. My only observation is that mentoring takes a significant amount of time to provide a students with a good experience. My guess is that I spent ~10 hours/week.

Also, I am pretty sure that a while back NumFOCUS joined as a GSoC org and that we would need to go through them (I could be wrong, but we should check with them).

**Comment by fcollonval** [comment]
@ellisonbg thanks for the inside - would you mind sending me the details of a contact person at NumFOCUS?

**Comment by fcollonval** [comment]
cc @HaoZeke @henrykironde

I'm putting in place the long form document right now. I'll let you know when it is done.

**Comment by fcollonval** [comment]
@krassowski @echarles thanks for proposing your help with mentoring GSoC. I updated the top comment with the link to the single document page listing the ideas.

I propose to keep this issue opened to discuss GSoC ideas and related topics.

**Comment by fcollonval** [comment]
Quick update - NumFocus has been accepted as organization for GSoC 2024. So JupyterLab ideas are eligible through that umbrella.

I have been contacted by two potential candidates. One interested by the builder refactor idea and the other by the toolkit integration.

**Comment by fcollonval** [comment]
Closing as the accepted proposals have been announced:

Ronan will work on [refactoring out the builder in a dedicated package](https://github.com/jupyterlab/frontends-team-compass/wiki/GSoC-2024#idea-3---create-a-swiss-army-knife-builder-cli)
Ashok will work on [defining extension entry points through JSON](https://github.com/jupyterlab/frontends-team-compass/wiki/GSoC-2024#idea-2----make-the-plugin-system-data-based) to only load features needed upon their request by the user
Mehak will work on using the [Jupyter toolkit to have a more homogeneous user experience](https://github.com/jupyterlab/frontends-team-compass/wiki/GSoC-2024#idea-1---improve-user-experience-using-the-jupyter-toolkit)
