### ISSUE TITLE
Advertise new version through NumFocus

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/frontends-team-compass#244]
### Problem

NumFocus is publishing a blog post (and a newsletter) with software updates; see for example the [February 2024 post](https://numfocus.medium.com/whats-new-with-numfocus-projects-february-2024-fe253a5e843a)

It would be interesting to be part of those updates - may be it should be an action for the Jupyter Community group to proxy all Jupyter sub-project updates to a single update to NumFOCUS.

### Proposed Solution

I contact NumFOCUS to learn the process for submitting such updates

**Comment by fcollonval** [comment]
I contact NumFocus but did not get an answer. I sent a email today specifically to the newsletter author. Hopefully I'll get an answer.

**Comment by jtpio** [comment]
Looks like we can now close this issue as a follow-up to the [move to the Linux foundation](https://www.linuxfoundation.org/press/linux-foundation-announces-formation-of-the-jupyter-foundation)?
