### ISSUE TITLE
Proposal to fold accessibility meeting into frontends weekly meeting

### ISSUE THREAD

**Issue by ohrely** [jupyterlab/frontends-team-compass#252]
### Problem

There is not enough activity/bandwidth within the Jupyter accessibility community to make effective use of the current twice-monthly meeting blocks.

### Proposed Solution

Merge accessibility meetings into frontends meetings:

- Rebrand the existing weekly Wednesday Jupyter Frontends meeting to a Jupyter Frontends and Accessibility meeting.
- Remove the existing alternating Thursdays accessibility meeting from the [Jupyter Community Calendar](https://discourse.jupyter.org/t/jupyter-community-calendar/2485).
- Advertise that accessibility topics are welcome in all of the combined meetings but members of the accessibility subproject will make a particular effort to attend the first meeting of each calendar month.
    - While most accessibility meeting regulars are already also frontends meeting regulars, prioritizing this way should reduce the burden on accessibility contributors who prefer not to attend all four/five calls per month.

### Additional context

This proposal has broad support from the accessibility community; see consensus-gathering at https://github.com/jupyter/accessibility/issues/148.

Unlike the recent merging of the lab and notebook subprojects into frontends, accessibility and frontends would continue to exist as two distinct subprojects.  This proposal is inspired by the combination of the server and kernels meetings.

**Comment by ohrely** [comment]
Copying in my thoughts from https://github.com/jupyter/accessibility/issues/148#issuecomment-2168884746:

I am personally enthusiastic about this proposal.

As an accessibility council member, I expect our efforts would benefit enormously from the additional attention and expertise of the frontends community. Products owned by frontends represent a significant proportion of the accessibility improvements urgently needed across Jupyter. Sustaining meeting momentum would cease to be a concern. We would likely catch the attention of potential contributors who wouldn't otherwise know there was an accessibility effort to join.

As a frontends council member, I see only upsides to combining the two meetings. Accessibility should be a key consideration in any changes that impact lab and notebook users. Accessibility pitfalls may get caught earlier in design/implementation discussions, saving effort at the review stage. Frontends contributors who want to get more engaged in accessibility can get involved without an extra meeting to attend (especially valuable for folks in time zones where typical Jupyter meeting times are inconvenient).

**Comment by JasonWeill** [comment]
@ohrely Thank you for opening this! We consistently get at least 10 attendees at most of our frontends meetings, and we rarely need the full hour, so I think that adding accessibility topics will be good for the group. Accessibility should be thought of as a core feature, not a special interest, in Jupyter front-end apps.

**Comment by gabalafou** [comment]
Should we start a vote on this?

**Comment by gabalafou** [comment]
By the way, I don't actually know how to call a vote in this repo, so I will leave that to someone else :D 

I just left my last comment as a gentle nudge because don't want this to be left in limbo for too long :)

**Comment by ohrely** [comment]
I'd like to give folks until Monday to comment on the proposal.  I'll open votes in both team compasses then if no objections are raised.

**Comment by JasonWeill** [comment]
@ohrely Now that we've moved forward with this change, should this issue be closed, and should the a11y meeting on Thursdays be deleted from the shared Google Calendar? I have permissions to do both.

**Comment by gabalafou** [comment]
@JasonWeill, yes please update the Google Calendar when you get a chance! The old meeting is still showing up on the calendar for today, but it shouldn't. Here's my more detailed [request on Discourse](https://discourse.jupyter.org/t/jupyter-community-calendar/2485/19?u=gabalafou), which might be helpful:

I tried to see if I have access to the calendar account in Google, but it seems that I do not. Could someone with access to the calendar make the following two changes?

1. Delete the bi-weekly Thursday “Jupyter Accessibility Meeting”, starting with and including the meeting scheduled for today, July 11 and all subsequent
2. Retitle the weekly Wednesday “JupyterLab and Notebook frontends meeting” to “Jupyter Frontends and Accessibility”, starting with and including July 17 and all subsequent

**Comment by JasonWeill** [comment]
@gabalafou Thank you for clarifying! Both of these are done. Closing this issue, as it appears that all work is done.
