### ISSUE TITLE
Frontends meeting guide revision

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/frontends-team-compass#259]
Based on the [Jupyter host guide](https://jupyterlab-team-compass.readthedocs.io/en/latest/host-guide.html) revised by https://github.com/jupyter/jupyter/pull/731, including contributions from @marthacryan and @ericsnekbytes, I propose revising the top section of our [HackMD meeting minutes](https://hackmd.io/Y7fBMQPSQ1C08SDGI-fwtg) as follows:

https://gist.github.com/JasonWeill/b722f405b21ce3cea5828dd87241799b

This file is not source controlled, so please leave comments here. Thanks!

**Comment by krassowski** [comment]
Adding host guide on top of agenda will make it less useful as everyone will need to scroll down over it.

Shall we instead update: https://github.com/jupyterlab/frontends-team-compass/blob/main/docs/host-guide.md ?

Or are you also proposing some changes to the agenda template?

**Comment by JasonWeill** [comment]
@krassowski I could do that instead! Would make for an easier code review, too.
